# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-05T15:46:32+00:00

# 2 rule(s) in category 'aide'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('aide', True) %}

# xccdf_org.ssgproject.content_rule_aide_build_database
# Build and Test AIDE Database  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: Req-11.5, 11.5.2
aide_build_database:
  cmd.run:
    - name: "aide --init && mv -f /var/lib/aide/aide.db.new /var/lib/aide/aide.db"
    - creates: /var/lib/aide/aide.db
    - require:
        - pkg: aide

# xccdf_org.ssgproject.content_rule_aide_periodic_checking_systemd_timer
# Configure Systemd Timer Execution of AIDE  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: Req-11.5, 11.5.2
aidecheck_service:
  file.managed:
    - name: /etc/systemd/system/aidecheck.service
    - mode: "0644"
    - contents:
        - "[Unit]"
        - "Description=Aide Check"
        - ""
        - "[Service]"
        - "Type=simple"
        - "ExecStart=/usr/sbin/aide --check"
        - ""
        - "[Install]"
        - "WantedBy=multi-user.target"

aidecheck_timer:
  file.managed:
    - name: /etc/systemd/system/aidecheck.timer
    - mode: "0644"
    - contents:
        - "[Unit]"
        - "Description=Aide check every day at 05:00"
        - ""
        - "[Timer]"
        - "OnCalendar=*-*-* 05:00:00"
        - ""
        - "[Install]"
        - "WantedBy=multi-user.target"

aidecheck_daemon_reload:
  cmd.run:
    - name: systemctl daemon-reload
    - onchanges:
        - file: aidecheck_service
        - file: aidecheck_timer

aidecheck_timer_enabled:
  service.running:
    - name: aidecheck.timer
    - enable: True
    - require:
        - file: aidecheck_timer
        - cmd: aidecheck_daemon_reload

{%- endif %}
