# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T14:19:45+00:00

# 49 rule(s) in category 'audit'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('audit', True) %}

# xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_chmod
# Record Events that Modify the System's Discretionary Access Controls - chmod  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_dac_modification_chmod:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_dac_modification_chmod.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S chmod -F auid>=1000 -F auid!=unset -F key=perm_mod"
        - "-a always,exit -F arch=b64 -S chmod -F auid>=1000 -F auid!=unset -F key=perm_mod"

# xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_chown
# Record Events that Modify the System's Discretionary Access Controls - chown  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_dac_modification_chown:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_dac_modification_chown.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S chown -F auid>=1000 -F auid!=unset -F key=perm_mod"
        - "-a always,exit -F arch=b64 -S chown -F auid>=1000 -F auid!=unset -F key=perm_mod"

# xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_fchmod
# Record Events that Modify the System's Discretionary Access Controls - fchmod  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_dac_modification_fchmod:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_dac_modification_fchmod.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S fchmod -F auid>=1000 -F auid!=unset -F key=perm_mod"
        - "-a always,exit -F arch=b64 -S fchmod -F auid>=1000 -F auid!=unset -F key=perm_mod"

# xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_fchmodat
# Record Events that Modify the System's Discretionary Access Controls - fchmodat  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_dac_modification_fchmodat:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_dac_modification_fchmodat.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S fchmodat -F auid>=1000 -F auid!=unset -F key=perm_mod"
        - "-a always,exit -F arch=b64 -S fchmodat -F auid>=1000 -F auid!=unset -F key=perm_mod"

# xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_fchown
# Record Events that Modify the System's Discretionary Access Controls - fchown  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_dac_modification_fchown:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_dac_modification_fchown.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S fchown -F auid>=1000 -F auid!=unset -F key=perm_mod"
        - "-a always,exit -F arch=b64 -S fchown -F auid>=1000 -F auid!=unset -F key=perm_mod"

# xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_fchownat
# Record Events that Modify the System's Discretionary Access Controls - fchownat  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_dac_modification_fchownat:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_dac_modification_fchownat.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S fchownat -F auid>=1000 -F auid!=unset -F key=perm_mod"
        - "-a always,exit -F arch=b64 -S fchownat -F auid>=1000 -F auid!=unset -F key=perm_mod"

# xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_fremovexattr
# Record Events that Modify the System's Discretionary Access Controls - fremovexattr  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_dac_modification_fremovexattr:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_dac_modification_fremovexattr.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S fremovexattr -F auid>=1000 -F auid!=unset -F key=perm_mod"
        - "-a always,exit -F arch=b64 -S fremovexattr -F auid>=1000 -F auid!=unset -F key=perm_mod"

# xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_fsetxattr
# Record Events that Modify the System's Discretionary Access Controls - fsetxattr  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_dac_modification_fsetxattr:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_dac_modification_fsetxattr.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S fsetxattr -F auid>=1000 -F auid!=unset -F key=perm_mod"
        - "-a always,exit -F arch=b64 -S fsetxattr -F auid>=1000 -F auid!=unset -F key=perm_mod"

# xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_lchown
# Record Events that Modify the System's Discretionary Access Controls - lchown  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_dac_modification_lchown:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_dac_modification_lchown.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S lchown -F auid>=1000 -F auid!=unset -F key=perm_mod"
        - "-a always,exit -F arch=b64 -S lchown -F auid>=1000 -F auid!=unset -F key=perm_mod"

# xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_lremovexattr
# Record Events that Modify the System's Discretionary Access Controls - lremovexattr  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_dac_modification_lremovexattr:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_dac_modification_lremovexattr.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S lremovexattr -F auid>=1000 -F auid!=unset -F key=perm_mod"
        - "-a always,exit -F arch=b64 -S lremovexattr -F auid>=1000 -F auid!=unset -F key=perm_mod"

# xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_lsetxattr
# Record Events that Modify the System's Discretionary Access Controls - lsetxattr  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_dac_modification_lsetxattr:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_dac_modification_lsetxattr.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S lsetxattr -F auid>=1000 -F auid!=unset -F key=perm_mod"
        - "-a always,exit -F arch=b64 -S lsetxattr -F auid>=1000 -F auid!=unset -F key=perm_mod"

# xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_removexattr
# Record Events that Modify the System's Discretionary Access Controls - removexattr  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_dac_modification_removexattr:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_dac_modification_removexattr.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S removexattr -F auid>=1000 -F auid!=unset -F key=perm_mod"
        - "-a always,exit -F arch=b64 -S removexattr -F auid>=1000 -F auid!=unset -F key=perm_mod"

# xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_setxattr
# Record Events that Modify the System's Discretionary Access Controls - setxattr  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_dac_modification_setxattr:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_dac_modification_setxattr.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S setxattr -F auid>=1000 -F auid!=unset -F key=perm_mod"
        - "-a always,exit -F arch=b64 -S setxattr -F auid>=1000 -F auid!=unset -F key=perm_mod"

# xccdf_org.ssgproject.content_rule_audit_rules_enable_syscall_auditing
# Remove Default Configuration to Disable Syscall Auditing  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: CM-6(b), CM-6.1(iv), SRG-OS-000480-GPOS-00227, SLES-15-030820, SLES-15-750450450, SV-234981r991589_rule
audit_enable_syscall:
  cmd.run:
    - name: "sed -ri 's/^([[:space:]]*-a[[:space:]]+task,never)/#\\1/' /etc/audit/rules.d/*.rules"
    - onlyif: "grep -rqE '^[[:space:]]*-a[[:space:]]+task,never' /etc/audit/rules.d/"

# xccdf_org.ssgproject.content_rule_audit_rules_file_deletion_events_rename
# Ensure auditd Collects File Deletion Events by User - rename  [severity: medium]
# PCI-DSS: Req-10.2.7, 10.2.1.7, 10.2.1, 10.2
audit_frag_audit_rules_file_deletion_events_rename:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_file_deletion_events_rename.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S rename -F auid>=1000 -F auid!=unset -F key=delete"
        - "-a always,exit -F arch=b64 -S rename -F auid>=1000 -F auid!=unset -F key=delete"

# xccdf_org.ssgproject.content_rule_audit_rules_file_deletion_events_renameat
# Ensure auditd Collects File Deletion Events by User - renameat  [severity: medium]
# PCI-DSS: Req-10.2.7, 10.2.1.7, 10.2.1, 10.2
audit_frag_audit_rules_file_deletion_events_renameat:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_file_deletion_events_renameat.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S renameat -F auid>=1000 -F auid!=unset -F key=delete"
        - "-a always,exit -F arch=b64 -S renameat -F auid>=1000 -F auid!=unset -F key=delete"

# xccdf_org.ssgproject.content_rule_audit_rules_file_deletion_events_renameat2
# Ensure auditd Collects File Deletion Events by User - renameat2  [severity: medium]
# PCI-DSS: 10.2.1.7, 10.2.1, 10.2
audit_frag_audit_rules_file_deletion_events_renameat2:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_file_deletion_events_renameat2.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S renameat2 -F auid>=1000 -F auid!=unset -F key=delete"
        - "-a always,exit -F arch=b64 -S renameat2 -F auid>=1000 -F auid!=unset -F key=delete"

# xccdf_org.ssgproject.content_rule_audit_rules_file_deletion_events_rmdir
# Ensure auditd Collects File Deletion Events by User - rmdir  [severity: medium]
# PCI-DSS: Req-10.2.7, 10.2.1.7, 10.2.1, 10.2
audit_frag_audit_rules_file_deletion_events_rmdir:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_file_deletion_events_rmdir.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S rmdir -F auid>=1000 -F auid!=unset -F key=delete"
        - "-a always,exit -F arch=b64 -S rmdir -F auid>=1000 -F auid!=unset -F key=delete"

# xccdf_org.ssgproject.content_rule_audit_rules_file_deletion_events_unlink
# Ensure auditd Collects File Deletion Events by User - unlink  [severity: medium]
# PCI-DSS: Req-10.2.7, 10.2.1.7, 10.2.1, 10.2
audit_frag_audit_rules_file_deletion_events_unlink:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_file_deletion_events_unlink.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S unlink -F auid>=1000 -F auid!=unset -F key=delete"
        - "-a always,exit -F arch=b64 -S unlink -F auid>=1000 -F auid!=unset -F key=delete"

# xccdf_org.ssgproject.content_rule_audit_rules_file_deletion_events_unlinkat
# Ensure auditd Collects File Deletion Events by User - unlinkat  [severity: medium]
# PCI-DSS: Req-10.2.7, 10.2.1.7, 10.2.1, 10.2
audit_frag_audit_rules_file_deletion_events_unlinkat:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_file_deletion_events_unlinkat.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S unlinkat -F auid>=1000 -F auid!=unset -F key=delete"
        - "-a always,exit -F arch=b64 -S unlinkat -F auid>=1000 -F auid!=unset -F key=delete"

# xccdf_org.ssgproject.content_rule_audit_rules_immutable
# Make the auditd Configuration Immutable  [severity: medium]
# PCI-DSS: Req-10.5.2, 10.3.2, 10.3
audit_frag_immutable:
  file.managed:
    - name: /etc/audit/rules.d/zz-pci-immutable.rules
    - mode: "0640"
    - contents:
        - "# Set the audit configuration immutable (scap2salt)"
        - -e 2

# xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock
# Record Attempts to Alter Logon and Logout Events - faillock  [severity: medium]
# PCI-DSS: Req-10.2.3, 10.2.1.3, 10.2.1, 10.2
audit_frag_audit_rules_login_events_faillock:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_login_events_faillock.rules
    - mode: "0640"
    - contents:
        - -w /var/log/faillock -p wa -k logins

# xccdf_org.ssgproject.content_rule_audit_rules_login_events_lastlog
# Record Attempts to Alter Logon and Logout Events - lastlog  [severity: medium]
# PCI-DSS: Req-10.2.3, 10.2.1.3, 10.2.1, 10.2
audit_frag_audit_rules_login_events_lastlog:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_login_events_lastlog.rules
    - mode: "0640"
    - contents:
        - -w /var/log/lastlog -p wa -k logins

# xccdf_org.ssgproject.content_rule_audit_rules_login_events_tallylog
# Record Attempts to Alter Logon and Logout Events - tallylog  [severity: medium]
# PCI-DSS: Req-10.2.3, 10.2.1.3, 10.2.1, 10.2
audit_frag_audit_rules_login_events_tallylog:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_login_events_tallylog.rules
    - mode: "0640"
    - contents:
        - -w /var/log/tallylog -p wa -k logins

# xccdf_org.ssgproject.content_rule_audit_rules_mac_modification
# Record Events that Modify the System's Mandatory Access Controls  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_mac_modification:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_mac_modification.rules
    - mode: "0640"
    - contents:
        - -w /etc/selinux/ -p wa -k MAC-policy

# xccdf_org.ssgproject.content_rule_audit_rules_media_export
# Ensure auditd Collects Information on Exporting to Media (successful)  [severity: medium]
# PCI-DSS: Req-10.2.7, 10.2.1.7, 10.2.1, 10.2
audit_frag_audit_rules_media_export:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_media_export.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=unset -F key=export"
        - "-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=unset -F key=export"

# xccdf_org.ssgproject.content_rule_audit_rules_networkconfig_modification
# Record Events that Modify the System's Network Environment  [severity: medium]
# PCI-DSS: Req-10.5.5, 10.3.4, 10.3
audit_frag_audit_rules_networkconfig_modification:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_networkconfig_modification.rules
    - mode: "0640"
    - contents:
        - -w /etc/issue -p wa -k audit_rules_networkconfig_modification
        - -w /etc/issue.net -p wa -k audit_rules_networkconfig_modification
        - -w /etc/hosts -p wa -k audit_rules_networkconfig_modification
        - -w /etc/sysconfig/network -p wa -k audit_rules_networkconfig_modification
        - "-a always,exit -F arch=b32 -S sethostname -S setdomainname -F key=audit_rules_networkconfig_modification"
        - "-a always,exit -F arch=b64 -S sethostname -S setdomainname -F key=audit_rules_networkconfig_modification"

# xccdf_org.ssgproject.content_rule_audit_rules_session_events_btmp
# Record Attempts to Alter Process and Session Initiation Information btmp  [severity: medium]
# PCI-DSS: 10.2.1.3, 10.2.1, 10.2
audit_frag_audit_rules_session_events_btmp:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_session_events_btmp.rules
    - mode: "0640"
    - contents:
        - -w /var/log/btmp -p wa -k session

# xccdf_org.ssgproject.content_rule_audit_rules_session_events_utmp
# Record Attempts to Alter Process and Session Initiation Information utmp  [severity: medium]
# PCI-DSS: 10.2.1.3, 10.2.1, 10.2
audit_frag_audit_rules_session_events_utmp:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_session_events_utmp.rules
    - mode: "0640"
    - contents:
        - -w /var/run/utmp -p wa -k session

# xccdf_org.ssgproject.content_rule_audit_rules_session_events_wtmp
# Record Attempts to Alter Process and Session Initiation Information wtmp  [severity: medium]
# PCI-DSS: 10.2.1.3, 10.2.1, 10.2
audit_frag_audit_rules_session_events_wtmp:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_session_events_wtmp.rules
    - mode: "0640"
    - contents:
        - -w /var/log/wtmp -p wa -k session

# xccdf_org.ssgproject.content_rule_audit_rules_suid_privilege_function
# Record Events When Privileged Executables Are Run  [severity: medium]
# PCI-DSS: 10.2.1.2, 10.2.1, 10.2
audit_frag_audit_rules_suid_privilege_function:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_suid_privilege_function.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S execve -C uid!=euid -F euid=0 -F key=setuid"
        - "-a always,exit -F arch=b64 -S execve -C uid!=euid -F euid=0 -F key=setuid"

# xccdf_org.ssgproject.content_rule_audit_rules_sysadmin_actions
# Ensure auditd Collects System Administrator Actions  [severity: medium]
# PCI-DSS: Req-10.2.2, Req-10.2.5.b, 10.2.1.5, 10.2.1, 10.2
audit_frag_audit_rules_sysadmin_actions:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_sysadmin_actions.rules
    - mode: "0640"
    - contents:
        - -w /etc/sudoers -p wa -k actions
        - -w /etc/sudoers.d/ -p wa -k actions

# xccdf_org.ssgproject.content_rule_audit_rules_time_adjtimex
# Record attempts to alter time through adjtimex  [severity: medium]
# PCI-DSS: Req-10.4.2.b, 10.6.3, 10.6
audit_frag_audit_rules_time_adjtimex:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_time_adjtimex.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -F key=audit_time_rules"
        - "-a always,exit -F arch=b64 -S adjtimex -S settimeofday -F key=audit_time_rules"

# xccdf_org.ssgproject.content_rule_audit_rules_time_clock_settime
# Record Attempts to Alter Time Through clock_settime  [severity: medium]
# PCI-DSS: Req-10.4.2.b, 10.6.3, 10.6
audit_frag_audit_rules_time_clock_settime:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_time_clock_settime.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -S clock_settime -F a0=0x0 -F key=time-change"
        - "-a always,exit -F arch=b64 -S clock_settime -F a0=0x0 -F key=time-change"

# xccdf_org.ssgproject.content_rule_audit_rules_time_settimeofday
# Record attempts to alter time through settimeofday  [severity: medium]
# PCI-DSS: Req-10.4.2.b, 10.6.3, 10.6
audit_frag_audit_rules_time_settimeofday:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_time_settimeofday.rules
    - mode: "0640"
    - contents:
        - "# Duplicate rules omitted — covered by an earlier fragment."

# xccdf_org.ssgproject.content_rule_audit_rules_time_stime
# Record Attempts to Alter Time Through stime  [severity: medium]
# PCI-DSS: Req-10.4.2.b, 10.6.3, 10.6
audit_frag_audit_rules_time_stime:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_time_stime.rules
    - mode: "0640"
    - contents:
        - "# Duplicate rules omitted — covered by an earlier fragment."

# xccdf_org.ssgproject.content_rule_audit_rules_time_watch_localtime
# Record Attempts to Alter the localtime File  [severity: medium]
# PCI-DSS: Req-10.4.2.b, 10.6.3, 10.6
audit_frag_audit_rules_time_watch_localtime:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_time_watch_localtime.rules
    - mode: "0640"
    - contents:
        - -w /etc/localtime -p wa -k audit_time_rules

# xccdf_org.ssgproject.content_rule_audit_rules_usergroup_modification_group
# Record Events that Modify User/Group Information - /etc/group  [severity: medium]
# PCI-DSS: Req-10.2.5, 10.2.1.5, 10.2.1, 10.2
audit_frag_audit_rules_usergroup_modification_group:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_usergroup_modification_group.rules
    - mode: "0640"
    - contents:
        - -w /etc/group -p wa -k audit_rules_usergroup_modification

# xccdf_org.ssgproject.content_rule_audit_rules_usergroup_modification_gshadow
# Record Events that Modify User/Group Information - /etc/gshadow  [severity: medium]
# PCI-DSS: Req-10.2.5, 10.2.1.5, 10.2.1, 10.2
audit_frag_audit_rules_usergroup_modification_gshadow:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_usergroup_modification_gshadow.rules
    - mode: "0640"
    - contents:
        - -w /etc/gshadow -p wa -k audit_rules_usergroup_modification

# xccdf_org.ssgproject.content_rule_audit_rules_usergroup_modification_opasswd
# Record Events that Modify User/Group Information - /etc/security/opasswd  [severity: medium]
# PCI-DSS: Req-10.2.5, 10.2.1.5, 10.2.1, 10.2
audit_frag_audit_rules_usergroup_modification_opasswd:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_usergroup_modification_opasswd.rules
    - mode: "0640"
    - contents:
        - -w /etc/security/opasswd -p wa -k audit_rules_usergroup_modification

# xccdf_org.ssgproject.content_rule_audit_rules_usergroup_modification_passwd
# Record Events that Modify User/Group Information - /etc/passwd  [severity: medium]
# PCI-DSS: Req-10.2.5, 10.2.1.5, 10.2.1, 10.2
audit_frag_audit_rules_usergroup_modification_passwd:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_usergroup_modification_passwd.rules
    - mode: "0640"
    - contents:
        - -w /etc/passwd -p wa -k audit_rules_usergroup_modification

# xccdf_org.ssgproject.content_rule_audit_rules_usergroup_modification_shadow
# Record Events that Modify User/Group Information - /etc/shadow  [severity: medium]
# PCI-DSS: Req-10.2.5, 10.2.1.5, 10.2.1, 10.2
audit_frag_audit_rules_usergroup_modification_shadow:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_rules_usergroup_modification_shadow.rules
    - mode: "0640"
    - contents:
        - -w /etc/shadow -p wa -k audit_rules_usergroup_modification

# xccdf_org.ssgproject.content_rule_audit_sudo_log_events
# Record Attempts to perform maintenance activities  [severity: medium]
# PCI-DSS: Req-10.2.2, Req-10.2.5.b, 10.2.1.3, 10.2.1, 10.2
audit_frag_audit_sudo_log_events:
  file.managed:
    - name: /etc/audit/rules.d/pci-audit_sudo_log_events.rules
    - mode: "0640"
    - contents:
        - -w /var/log/sudo.log -p wa -k maintenance

# xccdf_org.ssgproject.content_rule_auditd_audispd_syslog_plugin_activated
# Configure auditd to use audispd's syslog plugin  [severity: medium]
# PCI-DSS: Req-10.5.3, 10.3.3, 10.3
auditd_conf_active:
  file.replace:
    - name: /etc/audit/plugins.d/syslog.conf
    - pattern: "^active\\s*=.*$"
    - repl: "active = yes"
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_auditd_data_retention_admin_space_left_action
# Configure auditd admin_space_left Action on Low Disk Space  [severity: medium]
# PCI-DSS: Req-10.7, 10.5.1, 10.5
auditd_conf_admin_space_left_action:
  file.replace:
    - name: /etc/audit/auditd.conf
    - pattern: "^admin_space_left_action\\s*=.*$"
    - repl: "admin_space_left_action = single"
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_auditd_data_retention_space_left
# Configure auditd space_left on Low Disk Space  [severity: medium]
# PCI-DSS: Req-10.7, 10.5.1, 10.5
auditd_conf_space_left:
  file.replace:
    - name: /etc/audit/auditd.conf
    - pattern: "^space_left\\s*=.*$"
    - repl: "space_left = 100"
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_auditd_data_retention_space_left_action
# Configure auditd space_left Action on Low Disk Space  [severity: medium]
# PCI-DSS: Req-10.7, 10.5.1, 10.5
auditd_conf_space_left_action:
  file.replace:
    - name: /etc/audit/auditd.conf
    - pattern: "^space_left_action\\s*=.*$"
    - repl: "space_left_action = email"
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_auditd_name_format
# Set type of computer node name logging in audit logs  [severity: medium]
# PCI-DSS: 10.2.2, 10.2
auditd_conf_name_format:
  file.replace:
    - name: /etc/audit/auditd.conf
    - pattern: "^name_format\\s*=.*$"
    - repl: "name_format = fqd"
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_directory_access_var_log_audit
# Record Access Events to Audit Log Directory  [severity: medium]
# PCI-DSS: 10.3.1, 10.3
audit_frag_directory_access_var_log_audit:
  file.managed:
    - name: /etc/audit/rules.d/pci-directory_access_var_log_audit.rules
    - mode: "0640"
    - contents:
        - "-a always,exit -F arch=b32 -F dir=/var/log/audit/ -F perm=r -F auid>=1000 -F auid!=unset -F key=access-audit-trail"
        - "-a always,exit -F arch=b64 -F dir=/var/log/audit/ -F perm=r -F auid>=1000 -F auid!=unset -F key=access-audit-trail"

# Reload audit rules once any fragment changes.
augenrules_load:
  cmd.run:
    - name: 'imm=no; auditctl -s 2>/dev/null | grep -q "^enabled 2" && imm=yes; augenrules --load 2>/dev/null || true; if [ "$imm" = yes ]; then echo "scap2salt: audit rules changed but the audit config is immutable (-e 2) - reboot required to load them." > /run/scap2salt-audit-reboot-required; logger -t scap2salt "audit rules changed; reboot required (audit immutable -e 2)" 2>/dev/null || true; fi'
    - onchanges:
      - file: audit_frag_audit_rules_dac_modification_chmod
      - file: audit_frag_audit_rules_dac_modification_chown
      - file: audit_frag_audit_rules_dac_modification_fchmod
      - file: audit_frag_audit_rules_dac_modification_fchmodat
      - file: audit_frag_audit_rules_dac_modification_fchown
      - file: audit_frag_audit_rules_dac_modification_fchownat
      - file: audit_frag_audit_rules_dac_modification_fremovexattr
      - file: audit_frag_audit_rules_dac_modification_fsetxattr
      - file: audit_frag_audit_rules_dac_modification_lchown
      - file: audit_frag_audit_rules_dac_modification_lremovexattr
      - file: audit_frag_audit_rules_dac_modification_lsetxattr
      - file: audit_frag_audit_rules_dac_modification_removexattr
      - file: audit_frag_audit_rules_dac_modification_setxattr
      - file: audit_frag_audit_rules_file_deletion_events_rename
      - file: audit_frag_audit_rules_file_deletion_events_renameat
      - file: audit_frag_audit_rules_file_deletion_events_renameat2
      - file: audit_frag_audit_rules_file_deletion_events_rmdir
      - file: audit_frag_audit_rules_file_deletion_events_unlink
      - file: audit_frag_audit_rules_file_deletion_events_unlinkat
      - file: audit_frag_immutable
      - file: audit_frag_audit_rules_login_events_faillock
      - file: audit_frag_audit_rules_login_events_lastlog
      - file: audit_frag_audit_rules_login_events_tallylog
      - file: audit_frag_audit_rules_mac_modification
      - file: audit_frag_audit_rules_media_export
      - file: audit_frag_audit_rules_networkconfig_modification
      - file: audit_frag_audit_rules_session_events_btmp
      - file: audit_frag_audit_rules_session_events_utmp
      - file: audit_frag_audit_rules_session_events_wtmp
      - file: audit_frag_audit_rules_suid_privilege_function
      - file: audit_frag_audit_rules_sysadmin_actions
      - file: audit_frag_audit_rules_time_adjtimex
      - file: audit_frag_audit_rules_time_clock_settime
      - file: audit_frag_audit_rules_time_settimeofday
      - file: audit_frag_audit_rules_time_stime
      - file: audit_frag_audit_rules_time_watch_localtime
      - file: audit_frag_audit_rules_usergroup_modification_group
      - file: audit_frag_audit_rules_usergroup_modification_gshadow
      - file: audit_frag_audit_rules_usergroup_modification_opasswd
      - file: audit_frag_audit_rules_usergroup_modification_passwd
      - file: audit_frag_audit_rules_usergroup_modification_shadow
      - file: audit_frag_audit_sudo_log_events
      - file: audit_frag_directory_access_var_log_audit

# Flag a pending audit-rule reboot (red in MLM until rebooted).
audit_reboot_required:
  cmd.run:
    - name: 'cat /run/scap2salt-audit-reboot-required; exit 1'
    - onlyif: 'test -e /run/scap2salt-audit-reboot-required'

# Restart auditd after an auditd.conf change.
auditd_restart:
  cmd.run:
    - name: service auditd restart
    - onchanges:
      - file: auditd_conf_active
      - file: auditd_conf_admin_space_left_action
      - file: auditd_conf_space_left
      - file: auditd_conf_space_left_action
      - file: auditd_conf_name_format

{%- endif %}
