# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-05T16:53:52+00:00

# 1 rule(s) in category 'limits'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('limits', True) %}

# xccdf_org.ssgproject.content_rule_disable_users_coredumps
# Disable Core Dumps for All Users  [severity: medium]
# PCI-DSS: 3.3.1.1, 3.3.1, 3.3
limits_disable_coredumps:
  file.managed:
    - name: /etc/security/limits.d/10-pci-coredump.conf
    - makedirs: True
    - mode: "0644"
    - contents:
        - "# Disable core dumps for all users (scap2salt, PCI-DSS)"
        - "* hard core 0"

{%- endif %}
