# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T14:51:39+00:00

# 12 rule(s) in category 'lineinfile'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('lineinfile', True) %}

# Ensure /etc/default/useradd exists before modifying it.
ensure__etc_default_useradd:
  file.managed:
    - name: /etc/default/useradd
    - makedirs: True
    - replace: False

# Ensure /etc/login.defs exists before modifying it.
ensure__etc_login_defs:
  file.managed:
    - name: /etc/login.defs
    - makedirs: True
    - replace: False

# Ensure /etc/ssh/sshd_config.d/01-complianceascode-reinforce-os-defaults.conf exists before modifying it.
ensure__etc_ssh_sshd_config_d_01_complianceascode_reinforce_os_defaults_conf:
  file.managed:
    - name: /etc/ssh/sshd_config.d/01-complianceascode-reinforce-os-defaults.conf
    - makedirs: True
    - replace: False

# xccdf_org.ssgproject.content_rule_account_disable_post_pw_expiration
# Set Account Expiration Following Inactivity  [severity: medium]
# PCI-DSS: Req-8.1.4, 8.2.6, 8.2
line__etc_default_useradd_INACTIVE:
  file.replace:
    - name: /etc/default/useradd
    - pattern: "^\\s*INACTIVE=.*$"
    - repl: "INACTIVE=90"
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_accounts_maximum_age_login_defs
# Set Password Maximum Age  [severity: medium]
# PCI-DSS: Req-8.2.4, 8.3.9, 8.3
line__etc_login_defs_PASS_MAX_DAYS:
  file.replace:
    - name: /etc/login.defs
    - pattern: "^\\s*PASS_MAX_DAYS\\s.*$"
    - repl: PASS_MAX_DAYS 90
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_accounts_password_warn_age_login_defs
# Set Password Warning Age  [severity: medium]
# PCI-DSS: Req-8.2.4, 8.3.9, 8.3
line__etc_login_defs_PASS_WARN_AGE:
  file.replace:
    - name: /etc/login.defs
    - pattern: "^\\s*PASS_WARN_AGE\\s.*$"
    - repl: PASS_WARN_AGE 7
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_accounts_tmout
# Set Interactive Session Timeout  [severity: medium]
# PCI-DSS: 8.6.1, 8.6
accounts_tmout:
  file.managed:
    - name: /etc/profile.d/autologout.sh
    - mode: "0755"
    - contents:
        - "# Interactive session timeout (scap2salt, PCI-DSS)"
        - "TMOUT=900"
        - readonly TMOUT
        - export TMOUT

# xccdf_org.ssgproject.content_rule_chronyd_run_as_chrony_user
# Ensure that chronyd is running under chrony user account  [severity: medium]
# PCI-DSS: 10.6.3, 10.6
chronyd_run_as_chrony:
  file.replace:
    - name: /etc/sysconfig/chronyd
    - pattern: "^OPTIONS=.*$"
    - repl: "OPTIONS=\"-u chrony\""
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_chronyd_specify_remote_server
# A remote time server for Chrony is configured  [severity: medium]
# PCI-DSS: Req-10.4.3, 10.6.2, 10.6
chrony_remote_server:
  file.replace:
    - name: /etc/chrony.conf
    - pattern: "^\\s*(server|pool)\\s+\\S+"
    - repl: "\\g<0>"
    - append_if_not_found: True
    - not_found_content: "server 0.suse.pool.ntp.org\nserver 1.suse.pool.ntp.org\nserver 2.suse.pool.ntp.org\nserver 3.suse.pool.ntp.org"

# xccdf_org.ssgproject.content_rule_disable_host_auth
# Disable Host-Based Authentication  [severity: medium]
# PCI-DSS: 8.3.1, 8.3
line__etc_ssh_sshd_config_d_01_complianceascode_reinforce_os_defaults_conf_HostbasedAuthentication:
  file.replace:
    - name: /etc/ssh/sshd_config.d/01-complianceascode-reinforce-os-defaults.conf
    - pattern: "^\\s*HostbasedAuthentication\\s.*$"
    - repl: HostbasedAuthentication no
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_no_direct_root_logins
# Direct root Logins Not Allowed  [severity: medium]
# PCI-DSS: 8.6.1, 8.6
securetty_empty:
  file.managed:
    - name: /etc/securetty
    - mode: "0600"
    - contents:
        - ""

# xccdf_org.ssgproject.content_rule_postfix_network_listening_disabled
# Disable Postfix Network Listening  [severity: medium]
# PCI-DSS: 1.4.2, 1.4
line__etc_postfix_main_cf_inet_interfaces:
  file.replace:
    - name: /etc/postfix/main.cf
    - pattern: "^\\s*inet_interfaces=.*$"
    - repl: "inet_interfaces=loopback-only"
    - append_if_not_found: True
    - onlyif: test -f /etc/postfix/main.cf

# xccdf_org.ssgproject.content_rule_securetty_root_login_console_only
# Restrict Virtual Console Root Logins  [severity: medium]
# PCI-DSS: 8.6.1, 8.6
securetty_no_vc:
  file.replace:
    - name: /etc/securetty
    - pattern: "^vc/[0-9].*$"
    - repl: ""

# xccdf_org.ssgproject.content_rule_set_password_hashing_algorithm_libuserconf
# Set Password Hashing Algorithm in /etc/libuser.conf  [severity: medium]
# PCI-DSS: Req-8.2.1, 8.3.2, 8.3
libuser_crypt_style:
  file.replace:
    - name: /etc/libuser.conf
    - pattern: "^\\s*crypt_style\\s*=.*$"
    - repl: "crypt_style = sha512"
    - append_if_not_found: False
    - onlyif: test -f /etc/libuser.conf

# xccdf_org.ssgproject.content_rule_set_password_hashing_algorithm_logindefs
# Set Password Hashing Algorithm in /etc/login.defs  [severity: medium]
# PCI-DSS: Req-8.2.1, 8.3.2, 8.3
line__etc_login_defs_ENCRYPT_METHOD:
  file.replace:
    - name: /etc/login.defs
    - pattern: "^\\s*ENCRYPT_METHOD\\s.*$"
    - repl: ENCRYPT_METHOD SHA512
    - append_if_not_found: True

{%- endif %}
