# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T14:51:39+00:00

# AppArmor MAC equivalence (target uses AppArmor, not SELinux).
# Satisfies the control intent of: audit_rules_mac_modification_etc_selinux, grub2_enable_selinux, package_libselinux_installed, selinux_confinement_of_daemons, selinux_policytype, selinux_state
# PCI-DSS: 1.2, 1.2.6, 10.3, 10.3.4, Req-10.5.5

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('mac', True) %}

# Guard: only apply AppArmor states if AppArmor is the active LSM.
# On SELinux systems (e.g. SLE 16) this directory does not exist and
# all states below are skipped.  Redeploy with --target sle16 for SELinux.
{%- if salt['file.directory_exists']('/sys/kernel/security/apparmor') %}

apparmor_packages:
  pkg.installed:
    - pkgs:
        - apparmor-parser
        - apparmor-profiles
        - apparmor-utils

apparmor_service:
  service.running:
    - name: apparmor
    - enable: True
    - require:
      - pkg: apparmor_packages

# Equivalent of grub2_enable_selinux: ensure the MAC is enabled at boot.
apparmor_grub_cmdline:
  file.replace:
    - name: /etc/default/grub
    - pattern: '^(GRUB_CMDLINE_LINUX=")(?![^"]*security=)(.*)"$'
    - repl: '\g<1>security=apparmor \g<2>"'
    - append_if_not_found: False

grub2_mkconfig:
  cmd.run:
    - name: grub2-mkconfig -o /boot/grub2/grub.cfg
    - onchanges:
      - file: apparmor_grub_cmdline

# Equivalent of selinux_state=enforcing: put all profiles in enforce mode.
apparmor_enforce_all:
  cmd.run:
    - name: aa-enforce /etc/apparmor.d/*
    - onchanges:
      - service: apparmor_service

# Equivalent of audit_rules_mac_modification_etc_selinux: audit MAC config edits.
apparmor_audit_config:
  file.managed:
    - name: /etc/audit/rules.d/pci-mac-apparmor.rules
    - mode: "0640"
    - contents:
        - -w /etc/apparmor.d/ -p wa -k MAC-policy
        - -w /etc/apparmor/ -p wa -k MAC-policy

{%- else %}
# AppArmor LSM not active on this system — MAC states skipped.
{%- endif %}

{%- endif %}
