# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T13:50:26+00:00

# 5 rule(s) in category 'rpm'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('rpm', True) %}

# xccdf_org.ssgproject.content_rule_ensure_gpgcheck_globally_activated
# Ensure gpgcheck Enabled In Main zypper Configuration  [severity: high]
# PCI-DSS: Req-6.2, 6.3.3, 6.3
zypp_gpgcheck:
  file.replace:
    - name: /etc/zypp/zypp.conf
    - pattern: "^#?\\s*gpgcheck\\s*=.*$"
    - repl: "gpgcheck = 1"
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_ensure_gpgcheck_never_disabled
# Ensure gpgcheck Enabled for All zypper Package Repositories  [severity: high]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: Req-6.2, 6.3.3, 6.3
zypp_repo_gpgcheck:
  cmd.run:
    - name: "sed -ri 's/^([[:space:]]*)(repo_|pkg_)?gpgcheck[[:space:]]*=[[:space:]]*(0|off)/\\1\\2gpgcheck = 1/' /etc/zypp/repos.d/*.repo"
    - onlyif: "grep -rqiE '^[[:space:]]*(repo_|pkg_)?gpgcheck[[:space:]]*=[[:space:]]*(0|off)' /etc/zypp/repos.d/"

# xccdf_org.ssgproject.content_rule_ensure_suse_gpgkey_installed
# Ensure SUSE GPG Key Installed  [severity: high]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: Req-6.2, 6.3.3, 6.3
import_suse_gpgkeys:
  cmd.run:
    - name: "for k in /usr/lib/rpm/gpg/*; do rpm --import \"$k\" 2>/dev/null || true; done"
    - onlyif: test -d /usr/lib/rpm/gpg

# xccdf_org.ssgproject.content_rule_rpm_verify_ownership
# Verify and Correct Ownership with RPM  [severity: high]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: Req-11.5, 11.5.2
rpm_verify_ownership:
  cmd.run:
    - name: "rpm -qa | xargs -r -n1 rpm --setugids 2>/dev/null || true"

# xccdf_org.ssgproject.content_rule_rpm_verify_permissions
# Verify and Correct File Permissions with RPM  [severity: high]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: Req-11.5, 11.5.2
rpm_verify_permissions:
  cmd.run:
    - name: "rpm -qa | xargs -r -n1 rpm --setperms 2>/dev/null || true"

{%- endif %}
