# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-03T02:52:23+00:00

# 7 rule(s) in category 'services'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('services', True) %}

# xccdf_org.ssgproject.content_rule_service_auditd_enabled
# Enable auditd Service  [severity: medium]
# PCI-DSS: Req-10.1, 10.2.1, 10.2
svc_on_auditd:
  service.running:
    - name: auditd
    - enable: True

# xccdf_org.ssgproject.content_rule_service_avahi-daemon_disabled
# Disable Avahi Server Software  [severity: medium]
# PCI-DSS: 2.2.4, 2.2
svc_off_avahi-daemon:
  service.dead:
    - name: avahi-daemon
    - enable: False

# xccdf_org.ssgproject.content_rule_service_chronyd_or_ntpd_enabled
# Enable the NTP Daemon  [severity: medium]
# PCI-DSS: Req-10.4.1, 10.6.1, 10.6
svc_on_chronyd_or_ntpd:
  service.running:
    - name: chronyd_or_ntpd
    - enable: True

# xccdf_org.ssgproject.content_rule_service_firewalld_enabled
# Verify firewalld Enabled  [severity: medium]
# PCI-DSS: 1.2.1, 1.2
svc_on_firewalld:
  service.running:
    - name: firewalld
    - enable: True

# xccdf_org.ssgproject.content_rule_service_nftables_disabled
# Verify nftables Service is Disabled  [severity: medium]
# PCI-DSS: 1.2.1, 1.2
svc_off_nftables:
  service.dead:
    - name: nftables
    - enable: False

# xccdf_org.ssgproject.content_rule_service_rpcbind_disabled
# Disable rpcbind Service  [severity: low]
# PCI-DSS: 2.2.4, 2.2
svc_off_rpcbind:
  service.dead:
    - name: rpcbind
    - enable: False

# xccdf_org.ssgproject.content_rule_service_rsyncd_disabled
# Ensure rsyncd service is disabled  [severity: medium]
# PCI-DSS: 2.2.4, 2.2
svc_off_rsyncd:
  service.dead:
    - name: rsyncd
    - enable: False

{%- endif %}
