# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T04:06:53+00:00

# 2 rule(s) in category 'coredump'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('coredump', True) %}

# xccdf_org.ssgproject.content_rule_coredump_disable_backtraces
# Disable core dump backtraces  [severity: medium]
# PCI-DSS: Req-3.2, 3.3.1.1, 3.3.1, 3.3
coredump_ProcessSizeMax:
  file.managed:
    - name: /etc/systemd/coredump.conf.d/00-pci-coredump_disable_backtraces.conf
    - makedirs: True
    - mode: "0644"
    - contents:
        - "[Coredump]"
        - "ProcessSizeMax=0"

# xccdf_org.ssgproject.content_rule_coredump_disable_storage
# Disable storing core dump  [severity: medium]
# PCI-DSS: Req-3.2, 3.3.1.1, 3.3.1, 3.3
coredump_Storage:
  file.managed:
    - name: /etc/systemd/coredump.conf.d/00-pci-coredump_disable_storage.conf
    - makedirs: True
    - mode: "0644"
    - contents:
        - "[Coredump]"
        - "Storage=none"

{%- endif %}
