# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-05T21:10:05+00:00

# 7 rule(s) in category 'dconf'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('dconf', True) %}

# xccdf_org.ssgproject.content_rule_dconf_gnome_disable_automount
# Disable GNOME3 Automounting  [severity: medium]
# PCI-DSS: 3.4.2, 3.4
dconf_set_dconf_gnome_disable_automount:
  file.managed:
    - name: /etc/dconf/db/gdm.d/00-pci-dconf_gnome_disable_automount
    - makedirs: True
    - mode: "0644"
    - contents:
        - "[org/gnome/desktop/media-handling]"
        - "\\automount=false"

dconf_lock_dconf_gnome_disable_automount:
  file.managed:
    - name: /etc/dconf/db/gdm.d/locks/00-pci-dconf_gnome_disable_automount
    - makedirs: True
    - mode: "0644"
    - contents:
        - /org/gnome/desktop/media-handling/automount

# xccdf_org.ssgproject.content_rule_dconf_gnome_disable_automount_open
# Disable GNOME3 Automount Opening  [severity: medium]
# PCI-DSS: 3.4.2, 3.4
dconf_set_dconf_gnome_disable_automount_open:
  file.managed:
    - name: /etc/dconf/db/gdm.d/00-pci-dconf_gnome_disable_automount_open
    - makedirs: True
    - mode: "0644"
    - contents:
        - "[org/gnome/desktop/media-handling]"
        - "\\automount-open=false"

dconf_lock_dconf_gnome_disable_automount_open:
  file.managed:
    - name: /etc/dconf/db/gdm.d/locks/00-pci-dconf_gnome_disable_automount_open
    - makedirs: True
    - mode: "0644"
    - contents:
        - /org/gnome/desktop/media-handling/automount-open

# xccdf_org.ssgproject.content_rule_dconf_gnome_screensaver_idle_activation_enabled
# Enable GNOME3 Screensaver Idle Activation  [severity: medium]
# PCI-DSS: Req-8.1.8, 8.2.8, 8.2
dconf_set_dconf_gnome_screensaver_idle_activation_enabled:
  file.managed:
    - name: /etc/dconf/db/gdm.d/00-pci-dconf_gnome_screensaver_idle_activation_enabled
    - makedirs: True
    - mode: "0644"
    - contents:
        - "[org/gnome/desktop/screensaver]"
        - "\\idle-activation-enabled=true"

dconf_lock_dconf_gnome_screensaver_idle_activation_enabled:
  file.managed:
    - name: /etc/dconf/db/gdm.d/locks/00-pci-dconf_gnome_screensaver_idle_activation_enabled
    - makedirs: True
    - mode: "0644"
    - contents:
        - /org/gnome/desktop/screensaver/idle-activation-enabled

# xccdf_org.ssgproject.content_rule_dconf_gnome_screensaver_idle_delay
# Set GNOME3 Screensaver Inactivity Timeout  [severity: medium]
# PCI-DSS: Req-8.1.8, 8.2.8, 8.2
dconf_set_dconf_gnome_screensaver_idle_delay:
  file.managed:
    - name: /etc/dconf/db/gdm.d/00-pci-dconf_gnome_screensaver_idle_delay
    - makedirs: True
    - mode: "0644"
    - contents:
        - "[org/gnome/desktop/session]"
        - "\\idle-delay=uint32 ${inactivity_timeout_value}"

dconf_lock_dconf_gnome_screensaver_idle_delay:
  file.managed:
    - name: /etc/dconf/db/gdm.d/locks/00-pci-dconf_gnome_screensaver_idle_delay
    - makedirs: True
    - mode: "0644"
    - contents:
        - /org/gnome/desktop/session/idle-delay

# xccdf_org.ssgproject.content_rule_dconf_gnome_screensaver_lock_delay
# Set GNOME3 Screensaver Lock Delay After Activation Period  [severity: medium]
# PCI-DSS: Req-8.1.8, 8.2.8, 8.2
dconf_set_dconf_gnome_screensaver_lock_delay:
  file.managed:
    - name: /etc/dconf/db/gdm.d/00-pci-dconf_gnome_screensaver_lock_delay
    - makedirs: True
    - mode: "0644"
    - contents:
        - "[org/gnome/desktop/screensaver]"
        - "\\lock-delay=uint32 ${var_screensaver_lock_delay}"

dconf_lock_dconf_gnome_screensaver_lock_delay:
  file.managed:
    - name: /etc/dconf/db/gdm.d/locks/00-pci-dconf_gnome_screensaver_lock_delay
    - makedirs: True
    - mode: "0644"
    - contents:
        - /org/gnome/desktop/screensaver/lock-delay

# xccdf_org.ssgproject.content_rule_dconf_gnome_screensaver_lock_enabled
# Enable GNOME3 Screensaver Lock After Idle Period  [severity: medium]
# PCI-DSS: Req-8.1.8, 8.2.8, 8.2
dconf_set_dconf_gnome_screensaver_lock_enabled:
  file.managed:
    - name: /etc/dconf/db/gdm.d/00-pci-dconf_gnome_screensaver_lock_enabled
    - makedirs: True
    - mode: "0644"
    - contents:
        - "[org/gnome/desktop/lockdown]"
        - "\\disable-lock-screen=false"

dconf_lock_dconf_gnome_screensaver_lock_enabled:
  file.managed:
    - name: /etc/dconf/db/gdm.d/locks/00-pci-dconf_gnome_screensaver_lock_enabled
    - makedirs: True
    - mode: "0644"
    - contents:
        - /org/gnome/desktop/lockdown/disable-lock-screen

# xccdf_org.ssgproject.content_rule_dconf_gnome_screensaver_mode_blank
# Implement Blank Screensaver  [severity: medium]
# PCI-DSS: Req-8.1.8, 8.2.8, 8.2
dconf_set_dconf_gnome_screensaver_mode_blank:
  file.managed:
    - name: /etc/dconf/db/gdm.d/00-pci-dconf_gnome_screensaver_mode_blank
    - makedirs: True
    - mode: "0644"
    - contents:
        - "[org/gnome/desktop/screensaver]"
        - "\\picture-uri=string ''"

dconf_lock_dconf_gnome_screensaver_mode_blank:
  file.managed:
    - name: /etc/dconf/db/gdm.d/locks/00-pci-dconf_gnome_screensaver_mode_blank
    - makedirs: True
    - mode: "0644"
    - contents:
        - /org/gnome/desktop/screensaver/picture-uri

# Apply dconf changes to the compiled databases.
dconf_update:
  cmd.run:
    - name: dconf update
    - onchanges:
      - file: dconf_set_dconf_gnome_disable_automount
      - file: dconf_lock_dconf_gnome_disable_automount
      - file: dconf_set_dconf_gnome_disable_automount_open
      - file: dconf_lock_dconf_gnome_disable_automount_open
      - file: dconf_set_dconf_gnome_screensaver_idle_activation_enabled
      - file: dconf_lock_dconf_gnome_screensaver_idle_activation_enabled
      - file: dconf_set_dconf_gnome_screensaver_idle_delay
      - file: dconf_lock_dconf_gnome_screensaver_idle_delay
      - file: dconf_set_dconf_gnome_screensaver_lock_delay
      - file: dconf_lock_dconf_gnome_screensaver_lock_delay
      - file: dconf_set_dconf_gnome_screensaver_lock_enabled
      - file: dconf_lock_dconf_gnome_screensaver_lock_enabled
      - file: dconf_set_dconf_gnome_screensaver_mode_blank
      - file: dconf_lock_dconf_gnome_screensaver_mode_blank

{%- endif %}
