# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T14:06:47+00:00

# 2 rule(s) in category 'grub'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('grub', True) %}

# xccdf_org.ssgproject.content_rule_grub2_audit_argument
# Enable Auditing for Processes Which Start Prior to the Audit Daemon  [severity: low]
# PCI-DSS: Req-10.3, 10.7.2, 10.7
grub_grub2_audit_argument:
  file.replace:
    - name: /etc/default/grub
    - pattern: "^(GRUB_CMDLINE_LINUX=\")(?![^\"]*audit=)(.*)\"$"
    - repl: "\\g<1>audit=1 \\g<2>\""
    - append_if_not_found: False

# xccdf_org.ssgproject.content_rule_grub2_audit_backlog_limit_argument
# Extend Audit Backlog Limit for the Audit Daemon  [severity: low]
# PCI-DSS: 10.7.2, 10.7
grub_grub2_audit_backlog_limit_argument:
  file.replace:
    - name: /etc/default/grub
    - pattern: "^(GRUB_CMDLINE_LINUX=\")(?![^\"]*audit_backlog_limit=)(.*)\"$"
    - repl: "\\g<1>audit_backlog_limit=8192 \\g<2>\""
    - append_if_not_found: False

# Regenerate grub config after a kernel cmdline change.
grub2_mkconfig_grub:
  cmd.run:
    - name: grub2-mkconfig -o /boot/grub2/grub.cfg
    - onchanges:
      - file: /etc/default/grub

{%- endif %}
