# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-05T21:10:05+00:00

include:
  - pci_dss.sysctl
  - pci_dss.packages
  - pci_dss.rpm
  - pci_dss.services
  - pci_dss.permissions
  - pci_dss.kernel_modules
  - pci_dss.sshd
  - pci_dss.lineinfile
  - pci_dss.pam
  - pci_dss.sudo
  - pci_dss.audit
  - pci_dss.dconf
  - pci_dss.coredump
  - pci_dss.grub
  - pci_dss.limits
  - pci_dss.aide
  - pci_dss.mac
