# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T13:50:27+00:00

# 3 rule(s) in category 'kernel_modules'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('kernel_modules', True) %}

# xccdf_org.ssgproject.content_rule_kernel_module_dccp_disabled
# Disable DCCP Support  [severity: medium]
# PCI-DSS: Req-1.4.2, 1.4.2, 1.4
kmod_disable_dccp:
  file.managed:
    - name: /etc/modprobe.d/dccp.conf
    - mode: "0644"
    - contents:
        - install dccp /bin/true
        - blacklist dccp

# xccdf_org.ssgproject.content_rule_kernel_module_sctp_disabled
# Disable SCTP Support  [severity: medium]
# PCI-DSS: Req-1.4.2, 1.4.2, 1.4
kmod_disable_sctp:
  file.managed:
    - name: /etc/modprobe.d/sctp.conf
    - mode: "0644"
    - contents:
        - install sctp /bin/true
        - blacklist sctp

# xccdf_org.ssgproject.content_rule_kernel_module_usb-storage_disabled
# Disable Modprobe Loading of USB Storage Driver  [severity: medium]
# PCI-DSS: 3.4.2, 3.4
kmod_disable_usb-storage:
  file.managed:
    - name: /etc/modprobe.d/usb-storage.conf
    - mode: "0644"
    - contents:
        - install usb-storage /bin/true
        - blacklist usb-storage

{%- endif %}
