# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T17:44:33+00:00

# 2 rule(s) in category 'pam'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('pam', True) %}

# xccdf_org.ssgproject.content_rule_set_password_hashing_algorithm_commonauth
# Set PAM's Common Authentication Hashing Algorithm  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: Req-8.2.1, 8.3.2, 8.3
pam_unix_set_password_hashing_algorithm_commonauth:
  cmd.run:
    - name: "f=/etc/pam.d/common-auth; grep -qE \"^[[:space:]]*auth[[:space:]]+sufficient[[:space:]]+pam_unix\\.so\" \"$f\" || echo \"auth sufficient pam_unix.so\" >> \"$f\"; grep -qE \"^[[:space:]]*auth[[:space:]]+sufficient[[:space:]]+pam_unix\\.so.*\\bsha512\\b\" \"$f\" || sed -ri \"s|(^[[:space:]]*auth[[:space:]]+sufficient[[:space:]]+pam_unix\\.so\\S*)|\\1 sha512|\" \"$f\""
    - unless: "f=/etc/pam.d/common-auth; grep -qE \"^[[:space:]]*auth[[:space:]]+sufficient[[:space:]]+pam_unix\\.so.*\\bsha512\\b\" \"$f\""

# xccdf_org.ssgproject.content_rule_use_pam_wheel_group_for_su
# Enforce Usage of pam_wheel with Group Parameter for su Authentication  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: 2.2.6, 2.2
pam_wheel_use_pam_wheel_group_for_su:
  cmd.run:
    - name: "f=/etc/pam.d/su; grep -qE \"^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so\" \"$f\" || echo \"auth required pam_wheel.so\" >> \"$f\"; if grep -qE \"^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so.*\\bgroup=\" \"$f\"; then sed -ri \"s|(^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so.*\\bgroup=)[^[:space:]]*|\\1sugroup|\" \"$f\"; else sed -ri \"s|(^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so\\S*)|\\1 group=sugroup|\" \"$f\"; fi; grep -qE \"^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so.*\\buse_uid\\b\" \"$f\" || sed -ri \"s|(^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so\\S*)|\\1 use_uid|\" \"$f\""
    - unless: "f=/etc/pam.d/su; grep -qE \"^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so.*\\bgroup=sugroup\\b\" \"$f\" && grep -qE \"^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so.*\\buse_uid\\b\" \"$f\""

{%- endif %}
