# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T15:12:09+00:00

# 52 rule(s) in category 'permissions'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('permissions', True) %}

# xccdf_org.ssgproject.content_rule_file_at_deny_not_exist
# Ensure that /etc/at.deny does not exist  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_absent_file_at_deny_not_exist:
  file.absent:
    - name: /etc/at.deny

# xccdf_org.ssgproject.content_rule_file_cron_deny_not_exist
# Ensure that /etc/cron.deny does not exist  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_absent_file_cron_deny_not_exist:
  file.absent:
    - name: /etc/cron.deny

# xccdf_org.ssgproject.content_rule_file_groupowner_at_allow
# Verify Group Who Owns /etc/at.allow file  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_groupowner_at_allow:
  file.managed:
    - name: /etc/at.allow
    - group: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_groupowner_backup_etc_group
# Verify Group Who Owns Backup group File  [severity: medium]
# PCI-DSS: Req-8.7, 2.2.6, 2.2
file_meta_file_groupowner_backup_etc_group:
  file.managed:
    - name: /etc/group-
    - group: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_groupowner_backup_etc_passwd
# Verify Group Who Owns Backup passwd File  [severity: medium]
# PCI-DSS: Req-8.7, 2.2.6, 2.2
file_meta_file_groupowner_backup_etc_passwd:
  file.managed:
    - name: /etc/passwd-
    - group: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_groupowner_backup_etc_shadow
# Verify User Who Owns Backup shadow File  [severity: medium]
# PCI-DSS: Req-8.7, 2.2.6, 2.2
file_meta_file_groupowner_backup_etc_shadow:
  file.managed:
    - name: /etc/shadow-
    - group: 15
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_groupowner_cron_allow
# Verify Group Who Owns /etc/cron.allow file  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_groupowner_cron_allow:
  file.managed:
    - name: /etc/cron.allow
    - group: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_groupowner_cron_d
# Verify Group Who Owns cron.d  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_groupowner_cron_d:
  file.directory:
    - name: /etc/cron.d
    - group: 0

# xccdf_org.ssgproject.content_rule_file_groupowner_cron_daily
# Verify Group Who Owns cron.daily  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_groupowner_cron_daily:
  file.directory:
    - name: /etc/cron.daily
    - group: 0

# xccdf_org.ssgproject.content_rule_file_groupowner_cron_hourly
# Verify Group Who Owns cron.hourly  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_groupowner_cron_hourly:
  file.directory:
    - name: /etc/cron.hourly
    - group: 0

# xccdf_org.ssgproject.content_rule_file_groupowner_cron_monthly
# Verify Group Who Owns cron.monthly  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_groupowner_cron_monthly:
  file.directory:
    - name: /etc/cron.monthly
    - group: 0

# xccdf_org.ssgproject.content_rule_file_groupowner_cron_weekly
# Verify Group Who Owns cron.weekly  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_groupowner_cron_weekly:
  file.directory:
    - name: /etc/cron.weekly
    - group: 0

# xccdf_org.ssgproject.content_rule_file_groupowner_crontab
# Verify Group Who Owns Crontab  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_groupowner_crontab:
  file.managed:
    - name: /etc/crontab
    - group: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_groupowner_etc_group
# Verify Group Who Owns group File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_groupowner_etc_group:
  file.managed:
    - name: /etc/group
    - group: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_groupowner_etc_issue_net
# Verify Group Ownership of System Login Banner for Remote Connections  [severity: medium]
# PCI-DSS: 1.2.8, 1.2
file_meta_file_groupowner_etc_issue_net:
  file.managed:
    - name: /etc/issue.net
    - group: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_groupowner_etc_passwd
# Verify Group Who Owns passwd File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_groupowner_etc_passwd:
  file.managed:
    - name: /etc/passwd
    - group: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_groupowner_etc_shadow
# Verify Group Who Owns shadow File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_groupowner_etc_shadow:
  file.managed:
    - name: /etc/shadow
    - group: 15
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_groupowner_grub2_cfg
# Verify /boot/grub2/grub.cfg Group Ownership  [severity: medium]
# PCI-DSS: Req-7.1, 2.2.6, 2.2
file_meta_file_groupowner_grub2_cfg:
  file.managed:
    - name: /boot/grub2/grub.cfg
    - group: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_owner_at_allow
# Verify User Who Owns /etc/at.allow file  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_owner_at_allow:
  file.managed:
    - name: /etc/at.allow
    - user: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_owner_backup_etc_group
# Verify User Who Owns Backup group File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_owner_backup_etc_group:
  file.managed:
    - name: /etc/group-
    - user: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_owner_backup_etc_passwd
# Verify User Who Owns Backup passwd File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_owner_backup_etc_passwd:
  file.managed:
    - name: /etc/passwd-
    - user: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_owner_backup_etc_shadow
# Verify Group Who Owns Backup shadow File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_owner_backup_etc_shadow:
  file.managed:
    - name: /etc/shadow-
    - user: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_owner_cron_allow
# Verify User Who Owns /etc/cron.allow file  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_owner_cron_allow:
  file.managed:
    - name: /etc/cron.allow
    - user: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_owner_cron_d
# Verify Owner on cron.d  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_owner_cron_d:
  file.directory:
    - name: /etc/cron.d
    - user: 0

# xccdf_org.ssgproject.content_rule_file_owner_cron_daily
# Verify Owner on cron.daily  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_owner_cron_daily:
  file.directory:
    - name: /etc/cron.daily
    - user: 0

# xccdf_org.ssgproject.content_rule_file_owner_cron_hourly
# Verify Owner on cron.hourly  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_owner_cron_hourly:
  file.directory:
    - name: /etc/cron.hourly
    - user: 0

# xccdf_org.ssgproject.content_rule_file_owner_cron_monthly
# Verify Owner on cron.monthly  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_owner_cron_monthly:
  file.directory:
    - name: /etc/cron.monthly
    - user: 0

# xccdf_org.ssgproject.content_rule_file_owner_cron_weekly
# Verify Owner on cron.weekly  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_owner_cron_weekly:
  file.directory:
    - name: /etc/cron.weekly
    - user: 0

# xccdf_org.ssgproject.content_rule_file_owner_crontab
# Verify Owner on crontab  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_owner_crontab:
  file.managed:
    - name: /etc/crontab
    - user: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_owner_etc_group
# Verify User Who Owns group File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_owner_etc_group:
  file.managed:
    - name: /etc/group
    - user: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_owner_etc_issue_net
# Verify ownership of System Login Banner for Remote Connections  [severity: medium]
# PCI-DSS: 1.2.8, 1.2
file_meta_file_owner_etc_issue_net:
  file.managed:
    - name: /etc/issue.net
    - user: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_owner_etc_passwd
# Verify User Who Owns passwd File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_owner_etc_passwd:
  file.managed:
    - name: /etc/passwd
    - user: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_owner_etc_shadow
# Verify User Who Owns shadow File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_owner_etc_shadow:
  file.managed:
    - name: /etc/shadow
    - user: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_owner_grub2_cfg
# Verify /boot/grub2/grub.cfg User Ownership  [severity: medium]
# PCI-DSS: Req-7.1, 2.2.6, 2.2
file_meta_file_owner_grub2_cfg:
  file.managed:
    - name: /boot/grub2/grub.cfg
    - user: 0
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_permissions_at_allow
# Verify Permissions on /etc/at.allow file  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_permissions_at_allow:
  file.managed:
    - name: /etc/at.allow
    - mode: "0640"
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_permissions_backup_etc_group
# Verify Permissions on Backup group File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_permissions_backup_etc_group:
  file.managed:
    - name: /etc/group-
    - mode: "0644"
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_permissions_backup_etc_passwd
# Verify Permissions on Backup passwd File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_permissions_backup_etc_passwd:
  file.managed:
    - name: /etc/passwd-
    - mode: "0644"
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_permissions_backup_etc_shadow
# Verify Permissions on Backup shadow File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_permissions_backup_etc_shadow:
  file.managed:
    - name: /etc/shadow-
    - mode: "0000"
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_permissions_cron_allow
# Verify Permissions on /etc/cron.allow file  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_permissions_cron_allow:
  file.managed:
    - name: /etc/cron.allow
    - mode: "0640"
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_permissions_cron_d
# Verify Permissions on cron.d  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_permissions_cron_d:
  file.directory:
    - name: /etc/cron.d
    - dir_mode: "0700"

# xccdf_org.ssgproject.content_rule_file_permissions_cron_daily
# Verify Permissions on cron.daily  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_permissions_cron_daily:
  file.directory:
    - name: /etc/cron.daily
    - dir_mode: "0700"

# xccdf_org.ssgproject.content_rule_file_permissions_cron_hourly
# Verify Permissions on cron.hourly  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_permissions_cron_hourly:
  file.directory:
    - name: /etc/cron.hourly
    - dir_mode: "0700"

# xccdf_org.ssgproject.content_rule_file_permissions_cron_monthly
# Verify Permissions on cron.monthly  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_permissions_cron_monthly:
  file.directory:
    - name: /etc/cron.monthly
    - dir_mode: "0700"

# xccdf_org.ssgproject.content_rule_file_permissions_cron_weekly
# Verify Permissions on cron.weekly  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_permissions_cron_weekly:
  file.directory:
    - name: /etc/cron.weekly
    - dir_mode: "0700"

# xccdf_org.ssgproject.content_rule_file_permissions_crontab
# Verify Permissions on crontab  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_permissions_crontab:
  file.managed:
    - name: /etc/crontab
    - mode: "0600"
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_permissions_etc_group
# Verify Permissions on group File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_permissions_etc_group:
  file.managed:
    - name: /etc/group
    - mode: "0644"
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_permissions_etc_issue_net
# Verify permissions on System Login Banner for Remote Connections  [severity: medium]
# PCI-DSS: 1.2.8, 1.2
file_meta_file_permissions_etc_issue_net:
  file.managed:
    - name: /etc/issue.net
    - mode: "0644"
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_permissions_etc_passwd
# Verify Permissions on passwd File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_permissions_etc_passwd:
  file.managed:
    - name: /etc/passwd
    - mode: "0644"
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_permissions_etc_shadow
# Verify Permissions on shadow File  [severity: medium]
# PCI-DSS: Req-8.7.c, 2.2.6, 2.2
file_meta_file_permissions_etc_shadow:
  file.managed:
    - name: /etc/shadow
    - mode: "0000"
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_permissions_grub2_cfg
# Verify /boot/grub2/grub.cfg Permissions  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_permissions_grub2_cfg:
  file.managed:
    - name: /boot/grub2/grub.cfg
    - mode: "0600"
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_file_permissions_sshd_config
# Verify Permissions on SSH Server config file  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
file_meta_file_permissions_sshd_config:
  file.managed:
    - name: /etc/ssh/sshd_config
    - mode: "0600"
    - replace: False
    - create: False

# xccdf_org.ssgproject.content_rule_permissions_local_var_log
# Verify permissions of log files  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: 10.3.1, 10.3
permissions_local_var_log:
  cmd.run:
    - name: "find /var/log/ -perm /u+xs,g+xws,o+xwrt -type f -exec chmod u-xs,g-xws,o-xwrt {} +"
    - onlyif: "test -n \"$(find /var/log/ -perm /u+xs,g+xws,o+xwrt -type f -print -quit 2>/dev/null)\""

{%- endif %}
