# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-05T16:53:53+00:00

# 8 rule(s) in category 'services'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('services', True) %}

# Install a drop-in for audit-rules.service so it exits cleanly
# when audit rules are already locked (immutable -e 2 flag set).
audit_rules_dropin_dir:
  file.directory:
    - name: /etc/systemd/system/audit-rules.service.d
    - mode: '0755'

audit_rules_immutable_dropin:
  file.managed:
    - name: /etc/systemd/system/audit-rules.service.d/pci-immutable.conf
    - mode: '0644'
    - contents:
        - '[Service]'
        - 'ExecStart='
        - "ExecStart=/bin/sh -c 'if auditctl -s 2>/dev/null | grep -q \"enabled 2\"; then echo \"Audit rules immutable (-e 2), skipping reload\"; exit 0; fi; /sbin/augenrules --load'"

audit_rules_dropin_reload:
  cmd.run:
    - name: systemctl daemon-reload
    - onchanges:
        - file: audit_rules_immutable_dropin

audit_prereq_reset:
  cmd.run:
    - name: "systemctl reset-failed audit-rules.service 2>/dev/null || true"
    - onlyif: "systemctl is-failed audit-rules.service 2>/dev/null"
    - require:
        - cmd: audit_rules_dropin_reload

# xccdf_org.ssgproject.content_rule_service_auditd_enabled
# Enable auditd Service  [severity: medium]
# PCI-DSS: Req-10.1, 10.2.1, 10.2
svc_on_auditd:
  service.running:
    - name: auditd
    - enable: True
    - require:
        - cmd: audit_prereq_reset

# xccdf_org.ssgproject.content_rule_service_avahi-daemon_disabled
# Disable Avahi Server Software  [severity: medium]
# PCI-DSS: 2.2.4, 2.2
svc_off_avahi-daemon:
  service.dead:
    - name: avahi-daemon
    - enable: False

# xccdf_org.ssgproject.content_rule_service_chronyd_or_ntpd_enabled
# Enable the NTP Daemon  [severity: medium]
# PCI-DSS: Req-10.4.1, 10.6.1, 10.6
svc_on_chronyd:
  service.running:
    - name: chronyd
    - enable: True

# xccdf_org.ssgproject.content_rule_service_firewalld_enabled
# Verify firewalld Enabled  [severity: medium]
# PCI-DSS: 1.2.1, 1.2
svc_on_firewalld:
  service.running:
    - name: firewalld
    - enable: True

# xccdf_org.ssgproject.content_rule_service_nftables_disabled
# Verify nftables Service is Disabled  [severity: medium]
# PCI-DSS: 1.2.1, 1.2
svc_off_nftables:
  service.dead:
    - name: nftables
    - enable: False

# xccdf_org.ssgproject.content_rule_service_rpcbind_disabled
# Disable rpcbind Service  [severity: low]
# PCI-DSS: 2.2.4, 2.2
svc_off_rpcbind:
  service.dead:
    - name: rpcbind
    - enable: False

# xccdf_org.ssgproject.content_rule_service_rsyncd_disabled
# Ensure rsyncd service is disabled  [severity: medium]
# PCI-DSS: 2.2.4, 2.2
svc_off_rsyncd:
  service.dead:
    - name: rsyncd
    - enable: False

# xccdf_org.ssgproject.content_rule_timer_logrotate_enabled
# Enable logrotate Timer  [severity: medium]
# PCI-DSS: Req-10.7, 10.5.1, 10.5
timer_logrotate:
  service.running:
    - name: logrotate.timer
    - enable: True

{%- endif %}
