# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-05T19:21:55+00:00

# 15 rule(s) in category 'sshd'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('sshd', True) %}

# Ensure the sshd drop-in directory and file exist before any file.replace.
sshd_dropin_create:
  file.managed:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - makedirs: True
    - replace: False
    - mode: "0600"

# xccdf_org.ssgproject.content_rule_sshd_disable_empty_passwords
# Disable SSH Access via Empty Passwords  [severity: high]
# PCI-DSS: Req-2.2.4, 2.2.6, 2.2
sshd_PermitEmptyPasswords:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^PermitEmptyPasswords\\s.*$"
    - repl: PermitEmptyPasswords no
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_disable_rhosts
# Disable SSH Support for .rhosts Files  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
sshd_IgnoreRhosts:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^IgnoreRhosts\\s.*$"
    - repl: IgnoreRhosts yes
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_disable_root_login
# Disable SSH Root Login  [severity: medium]
# PCI-DSS: Req-2.2.4, 2.2.6, 2.2
sshd_PermitRootLogin:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^PermitRootLogin\\s.*$"
    - repl: PermitRootLogin no
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_disable_tcp_forwarding
# Disable SSH TCP Forwarding  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
sshd_AllowTcpForwarding:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^AllowTcpForwarding\\s.*$"
    - repl: AllowTcpForwarding no
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_disable_x11_forwarding
# Disable X11 Forwarding  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
sshd_X11Forwarding:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^X11Forwarding\\s.*$"
    - repl: X11Forwarding no
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_do_not_permit_user_env
# Do Not Allow SSH Environment Options  [severity: medium]
# PCI-DSS: Req-2.2.4, 2.2.6, 2.2
sshd_PermitUserEnvironment:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^PermitUserEnvironment\\s.*$"
    - repl: PermitUserEnvironment no
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_enable_pam
# Enable PAM  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
sshd_UsePAM:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^UsePAM\\s.*$"
    - repl: UsePAM yes
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout
# Set SSH Client Alive Interval  [severity: medium]
# PCI-DSS: Req-8.1.8, 8.2.8, 8.2
sshd_ClientAliveInterval:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^ClientAliveInterval\\s.*$"
    - repl: ClientAliveInterval 300
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_set_keepalive
# Set SSH Client Alive Count Max  [severity: medium]
# PCI-DSS: Req-8.1.8, 8.2.8, 8.2
sshd_ClientAliveCountMax:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^ClientAliveCountMax\\s.*$"
    - repl: ClientAliveCountMax 1
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_set_login_grace_time
# Ensure SSH LoginGraceTime is configured  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
sshd_LoginGraceTime:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^LoginGraceTime\\s.*$"
    - repl: LoginGraceTime 60
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_set_loglevel_verbose
# Set SSH Daemon LogLevel to VERBOSE  [severity: medium]
# PCI-DSS: Req-2.2.4, 2.2.6, 2.2
sshd_LogLevel:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^LogLevel\\s.*$"
    - repl: LogLevel VERBOSE
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_set_max_auth_tries
# Set SSH authentication attempt limit  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
sshd_MaxAuthTries:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^MaxAuthTries\\s.*$"
    - repl: MaxAuthTries 4
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_set_max_sessions
# Set SSH MaxSessions limit  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
sshd_MaxSessions:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^MaxSessions\\s.*$"
    - repl: MaxSessions 10
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_set_maxstartups
# Ensure SSH MaxStartups is configured  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
sshd_MaxStartups:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^MaxStartups\\s.*$"
    - repl: "MaxStartups 10:30:100"
    - append_if_not_found: True

# xccdf_org.ssgproject.content_rule_sshd_use_strong_kex
# Use Only Strong Key Exchange algorithms  [severity: medium]
# PCI-DSS: Req-2.3, 2.2.7, 2.2
sshd_KexAlgorithms:
  file.replace:
    - name: /etc/ssh/sshd_config.d/00-pci-hardening.conf
    - pattern: "^KexAlgorithms\\s.*$"
    - repl: "KexAlgorithms ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256"
    - append_if_not_found: True

{%- endif %}
