# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T17:44:33+00:00

# 3 rule(s) in category 'sudo'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('sudo', True) %}

# xccdf_org.ssgproject.content_rule_sudo_add_use_pty
# Ensure Only Users Logged In To Real tty Can Execute Sudo - sudo use_pty  [severity: medium]
# PCI-DSS: Req-10.2.5, 2.2.6, 2.2
sudoers_sudo_add_use_pty:
  file.managed:
    - name: /etc/sudoers.d/99-pci-sudo_add_use_pty
    - mode: "0440"
    - contents:
        - Defaults use_pty

# xccdf_org.ssgproject.content_rule_sudo_custom_logfile
# Ensure Sudo Logfile Exists - sudo logfile  [severity: low]
# PCI-DSS: Req-10.2.5, 2.2.6, 2.2
sudoers_sudo_custom_logfile:
  file.managed:
    - name: /etc/sudoers.d/99-pci-sudo_custom_logfile
    - mode: "0440"
    - contents:
        - "Defaults logfile=/var/log/sudo.log"

# xccdf_org.ssgproject.content_rule_sudo_require_reauthentication
# Require Re-Authentication When Using the sudo Command  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
sudoers_sudo_require_reauthentication:
  file.managed:
    - name: /etc/sudoers.d/99-pci-sudo_require_reauthentication
    - mode: "0440"
    - contents:
        - "Defaults timestamp_timeout=5"

{%- endif %}
