# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T04:06:53+00:00

# 12 rule(s) in category 'sysctl'.

{%- set p = salt['pillar.get']('pci_dss', {}) %}
{%- if p.get('enabled', True) and p.get('sysctl', True) %}

# xccdf_org.ssgproject.content_rule_sysctl_fs_suid_dumpable
# Disable Core Dumps for SUID programs  [severity: medium]
# PCI-DSS: 3.3.1.1, 3.3.1, 3.3
sysctl_fs.suid_dumpable:
  sysctl.present:
    - name: fs.suid_dumpable
    - value: 0
    - config: /etc/sysctl.d/fs_suid_dumpable.conf

# xccdf_org.ssgproject.content_rule_sysctl_kernel_randomize_va_space
# Enable Randomized Layout of Virtual Address Space  [severity: medium]
# PCI-DSS: Req-2.2.1, 3.3.1.1, 3.3.1, 3.3
sysctl_kernel.randomize_va_space:
  sysctl.present:
    - name: kernel.randomize_va_space
    - value: 2
    - config: /etc/sysctl.d/kernel_randomize_va_space.conf

# xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_conf_all_rp_filter
# Enable Kernel Parameter to Use Reverse Path Filtering on all IPv4 Interfaces  [severity: medium]
# PCI-DSS: Req-1.4.3, 1.4.3, 1.4
sysctl_net.ipv4.conf.all.rp_filter:
  sysctl.present:
    - name: net.ipv4.conf.all.rp_filter
    - value: 1
    - config: /etc/sysctl.d/net_ipv4_conf_all_rp_filter.conf

# xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_conf_all_secure_redirects
# Disable Kernel Parameter for Accepting Secure ICMP Redirects on all IPv4 Interfaces  [severity: medium]
# PCI-DSS: Req-1.4.3, 1.4.3, 1.4
sysctl_net.ipv4.conf.all.secure_redirects:
  sysctl.present:
    - name: net.ipv4.conf.all.secure_redirects
    - value: 0
    - config: /etc/sysctl.d/net_ipv4_conf_all_secure_redirects.conf

# xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_conf_all_send_redirects
# Disable Kernel Parameter for Sending ICMP Redirects on all IPv4 Interfaces  [severity: medium]
# PCI-DSS: 1.4.5, 1.4
sysctl_net.ipv4.conf.all.send_redirects:
  sysctl.present:
    - name: net.ipv4.conf.all.send_redirects
    - value: 0
    - config: /etc/sysctl.d/net_ipv4_conf_all_send_redirects.conf

# xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_conf_default_accept_redirects
# Disable Kernel Parameter for Accepting ICMP Redirects by Default on IPv4 Interfaces  [severity: medium]
# PCI-DSS: Req-1.4.3, 1.4.3, 1.4
sysctl_net.ipv4.conf.default.accept_redirects:
  sysctl.present:
    - name: net.ipv4.conf.default.accept_redirects
    - value: 0
    - config: /etc/sysctl.d/net_ipv4_conf_default_accept_redirects.conf

# xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_conf_default_send_redirects
# Disable Kernel Parameter for Sending ICMP Redirects on all IPv4 Interfaces by Default  [severity: medium]
# PCI-DSS: 1.4.5, 1.4
sysctl_net.ipv4.conf.default.send_redirects:
  sysctl.present:
    - name: net.ipv4.conf.default.send_redirects
    - value: 0
    - config: /etc/sysctl.d/net_ipv4_conf_default_send_redirects.conf

# xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_icmp_echo_ignore_broadcasts
# Enable Kernel Parameter to Ignore ICMP Broadcast Echo Requests on IPv4 Interfaces  [severity: medium]
# PCI-DSS: Req-1.4.3, 1.4.2, 1.4
sysctl_net.ipv4.icmp_echo_ignore_broadcasts:
  sysctl.present:
    - name: net.ipv4.icmp_echo_ignore_broadcasts
    - value: 1
    - config: /etc/sysctl.d/net_ipv4_icmp_echo_ignore_broadcasts.conf

# xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_icmp_ignore_bogus_error_responses
# Enable Kernel Parameter to Ignore Bogus ICMP Error Responses on IPv4 Interfaces  [severity: unknown]
# PCI-DSS: Req-1.4.3, 1.4.2, 1.4
sysctl_net.ipv4.icmp_ignore_bogus_error_responses:
  sysctl.present:
    - name: net.ipv4.icmp_ignore_bogus_error_responses
    - value: 1
    - config: /etc/sysctl.d/net_ipv4_icmp_ignore_bogus_error_responses.conf

# xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_ip_forward
# Disable Kernel Parameter for IP Forwarding on IPv4 Interfaces  [severity: medium]
# PCI-DSS: Req-1.3.1, Req-1.3.2, 1.4.3, 1.4
sysctl_net.ipv4.ip_forward:
  sysctl.present:
    - name: net.ipv4.ip_forward
    - value: 0
    - config: /etc/sysctl.d/net_ipv4_ip_forward.conf

# xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_tcp_syncookies
# Enable Kernel Parameter to Use TCP Syncookies on Network Interfaces  [severity: medium]
# PCI-DSS: Req-1.4.1, 1.4.3, 1.4
sysctl_net.ipv4.tcp_syncookies:
  sysctl.present:
    - name: net.ipv4.tcp_syncookies
    - value: 1
    - config: /etc/sysctl.d/net_ipv4_tcp_syncookies.conf

# xccdf_org.ssgproject.content_rule_sysctl_net_ipv6_conf_default_accept_source_route
# Disable Kernel Parameter for Accepting Source-Routed Packets on IPv6 Interfaces by Default  [severity: medium]
# PCI-DSS: Req-1.4.3, 1.4.2, 1.4
sysctl_net.ipv6.conf.default.accept_source_route:
  sysctl.present:
    - name: net.ipv6.conf.default.accept_source_route
    - value: 0
    - config: /etc/sysctl.d/net_ipv6_conf_default_accept_source_route.conf

{%- endif %}
