# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-07T14:20:24+00:00

# 2 rule(s) in category 'firewall'.
# NOTE: SLE 15 defaults to firewalld (nftables backend). These raw
# iptables rules are faithful to the SCAP check but may need review for
# coexistence with a firewalld-managed ruleset. Requires the iptables
# package + Salt iptables module on the minion.

{%- set p = salt['pillar.get']('PCI_DSS_v4_SLE15', {}) %}
{%- if p.get('enabled', True) and p.get('firewall', True) %}

# xccdf_org.ssgproject.content_rule_set_ipv6_loopback_traffic
# Set configuration for IPv6 loopback traffic  [severity: medium]
# PCI-DSS: Req-1.3, 1.4.1, 1.4
fw_set_ipv6_loopback_traffic_0:
  iptables.append:
    - table: filter
    - chain: INPUT
    - jump: ACCEPT
    - in-interface: lo
    - family: ipv6
    - save: True

fw_set_ipv6_loopback_traffic_1:
  iptables.append:
    - table: filter
    - chain: OUTPUT
    - jump: ACCEPT
    - out-interface: lo
    - family: ipv6
    - save: True

fw_set_ipv6_loopback_traffic_2:
  iptables.append:
    - table: filter
    - chain: INPUT
    - jump: DROP
    - source: "::1"
    - family: ipv6
    - save: True

# xccdf_org.ssgproject.content_rule_set_loopback_traffic
# Set configuration for loopback traffic  [severity: medium]
# PCI-DSS: Req-1.3, 1.4.1, 1.4
fw_set_loopback_traffic_0:
  iptables.append:
    - table: filter
    - chain: INPUT
    - jump: ACCEPT
    - in-interface: lo
    - family: ipv4
    - save: True

fw_set_loopback_traffic_1:
  iptables.append:
    - table: filter
    - chain: OUTPUT
    - jump: ACCEPT
    - out-interface: lo
    - family: ipv4
    - save: True

fw_set_loopback_traffic_2:
  iptables.append:
    - table: filter
    - chain: INPUT
    - jump: DROP
    - source: 127.0.0.0/8
    - family: ipv4
    - save: True

{%- endif %}
