# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T17:53:57+00:00

include:
  - PCI_DSS_v4_SLE15.sysctl
  - PCI_DSS_v4_SLE15.packages
  - PCI_DSS_v4_SLE15.rpm
  - PCI_DSS_v4_SLE15.services
  - PCI_DSS_v4_SLE15.permissions
  - PCI_DSS_v4_SLE15.kernel_modules
  - PCI_DSS_v4_SLE15.sshd
  - PCI_DSS_v4_SLE15.lineinfile
  - PCI_DSS_v4_SLE15.accounts
  - PCI_DSS_v4_SLE15.pam
  - PCI_DSS_v4_SLE15.sudo
  - PCI_DSS_v4_SLE15.audit
  - PCI_DSS_v4_SLE15.dconf
  - PCI_DSS_v4_SLE15.coredump
  - PCI_DSS_v4_SLE15.grub
  - PCI_DSS_v4_SLE15.firewall
  - PCI_DSS_v4_SLE15.limits
  - PCI_DSS_v4_SLE15.aide
  - PCI_DSS_v4_SLE15.mac
