# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T17:44:33+00:00

base:
  # Target your PCI in-scope SUSE clients here (grain/group match).
  'G@os_family:Suse and G@pci_scope:true':
    - match: compound
    - pci_dss
