# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T17:54:04+00:00

include:
  - PCI_DSS_v4_SLE16.sysctl
  - PCI_DSS_v4_SLE16.packages
  - PCI_DSS_v4_SLE16.rpm
  - PCI_DSS_v4_SLE16.services
  - PCI_DSS_v4_SLE16.permissions
  - PCI_DSS_v4_SLE16.kernel_modules
  - PCI_DSS_v4_SLE16.sshd
  - PCI_DSS_v4_SLE16.lineinfile
  - PCI_DSS_v4_SLE16.accounts
  - PCI_DSS_v4_SLE16.pam
  - PCI_DSS_v4_SLE16.sudo
  - PCI_DSS_v4_SLE16.audit
  - PCI_DSS_v4_SLE16.dconf
  - PCI_DSS_v4_SLE16.coredump
  - PCI_DSS_v4_SLE16.grub
  - PCI_DSS_v4_SLE16.limits
  - PCI_DSS_v4_SLE16.aide
  - PCI_DSS_v4_SLE16.mac
