# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle16-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-07T14:20:24+00:00

# 3 rule(s) in category 'mac'.

{%- set p = salt['pillar.get']('PCI_DSS_v4_SLE16', {}) %}
{%- if p.get('enabled', True) and p.get('mac', True) %}

# xccdf_org.ssgproject.content_rule_grub2_enable_selinux
# Ensure SELinux Not Disabled in /etc/default/grub  [severity: medium]
# PCI-DSS: 1.2.6, 1.2
grub_security_selinux:
  file.replace:
    - name: /etc/default/grub
    - pattern: "^(GRUB_CMDLINE_LINUX=\")(?![^\"]*security=)(.*)\"$"
    - repl: "\\g<1>security=selinux \\g<2>\""
    - append_if_not_found: False
    - backup: False

# xccdf_org.ssgproject.content_rule_selinux_policytype
# Configure SELinux Policy  [severity: medium]
# PCI-DSS: 1.2.6, 1.2
selinux_policytype:
  file.replace:
    - name: /etc/selinux/config
    - pattern: "^SELINUXTYPE=.*$"
    - repl: "SELINUXTYPE=targeted"
    - append_if_not_found: True
    - backup: False

# xccdf_org.ssgproject.content_rule_selinux_state
# Ensure SELinux State is Enforcing  [severity: high]
# PCI-DSS: 1.2.6, 1.2
selinux_enforcing:
  selinux.mode:
    - name: enforcing

# Regenerate grub config after a kernel cmdline change.
grub2_mkconfig_mac:
  cmd.run:
    - name: grub2-mkconfig -o /boot/grub2/grub.cfg
    - onchanges:
      - file: /etc/default/grub

{%- endif %}
