# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-03T03:00:01+00:00

pci_dss:
  enabled: True
  sysctl: True
  packages: True
  services: True
  permissions: True
  kernel_modules: True
  sshd: True
  lineinfile: True
  pam: True
  sudo: True
  audit: True
  dconf: True
  coredump: True
  grub: True
  firewall: True
  limits: True
  aide: True
  rpm: True
  mac: True
