# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T17:24:28+00:00

# 4 rule(s) in category 'accounts'.

{%- set p = salt['pillar.get']('pci_dss_sle15', {}) %}
{%- if p.get('enabled', True) and p.get('accounts', False) %}

# xccdf_org.ssgproject.content_rule_accounts_password_set_max_life_existing
# Set Existing Passwords Maximum Age  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: 8.3.9, 8.3
accounts_password_set_max_life_existing:
  cmd.run:
    - name: "awk -v var=90 -F: '(/^[^:]+:[^!*]/ && ($5 > var || $5 == \"\")) {print $1}' /etc/shadow | while IFS= read -r u; do passwd -q -x 90 \"$u\"; done"
    - onlyif: "test -n \"$(awk -v var=90 -F: '(/^[^:]+:[^!*]/ && ($5 > var || $5 == \"\")) {print $1}' /etc/shadow)\""

# xccdf_org.ssgproject.content_rule_accounts_password_set_warn_age_existing
# Set Existing Passwords Warning Age  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: 8.3.9, 8.3
accounts_password_set_warn_age_existing:
  cmd.run:
    - name: "awk -v var=7 -F: '(($6 < var || $6 == \"\") && $2 ~ /^\\$/) {print $1}' /etc/shadow | while IFS= read -r u; do chage --warndays 7 \"$u\"; done"
    - onlyif: "test -n \"$(awk -v var=7 -F: '(($6 < var || $6 == \"\") && $2 ~ /^\\$/) {print $1}' /etc/shadow)\""

# xccdf_org.ssgproject.content_rule_accounts_set_post_pw_existing
# Set existing passwords a period of inactivity before they been locked  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: Req-8.1.4, 8.2.6, 8.2
accounts_set_post_pw_existing:
  cmd.run:
    - name: "awk -v var=90 -F: '(($7 > var || $7 == \"\") && $2 ~ /^\\$/) {print $1}' /etc/shadow | while IFS= read -r u; do chage --inactive 90 \"$u\"; done"
    - onlyif: "test -n \"$(awk -v var=90 -F: '(($7 > var || $7 == \"\") && $2 ~ /^\\$/) {print $1}' /etc/shadow)\""

# xccdf_org.ssgproject.content_rule_sudo_require_authentication
# Ensure Users Re-Authenticate for Privilege Escalation - sudo  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: 2.2.6, 2.2
sudo_require_authentication:
  cmd.run:
    - name: "for f in /etc/sudoers /etc/sudoers.d/*; do [ -e \"$f\" ] || continue; sed -ri '/^[[:space:]]*[^#[:space:]].*(NOPASSWD|!authenticate)/ s/^/# /' \"$f\"; done"
    - onlyif: "grep -rEq '^[[:space:]]*[^#[:space:]].*(NOPASSWD|!authenticate)' /etc/sudoers /etc/sudoers.d/ 2>/dev/null"

{%- endif %}
