# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T17:44:33+00:00

include:
  - pci_dss_sle15.sysctl
  - pci_dss_sle15.packages
  - pci_dss_sle15.rpm
  - pci_dss_sle15.services
  - pci_dss_sle15.permissions
  - pci_dss_sle15.kernel_modules
  - pci_dss_sle15.sshd
  - pci_dss_sle15.lineinfile
  - pci_dss_sle15.accounts
  - pci_dss_sle15.pam
  - pci_dss_sle15.sudo
  - pci_dss_sle15.audit
  - pci_dss_sle15.dconf
  - pci_dss_sle15.coredump
  - pci_dss_sle15.grub
  - pci_dss_sle15.firewall
  - pci_dss_sle15.limits
  - pci_dss_sle15.aide
  - pci_dss_sle15.mac
