# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T17:30:52+00:00

# 22 rule(s) in category 'packages'.

{%- set p = salt['pillar.get']('pci_dss_sle15', {}) %}
{%- if p.get('enabled', True) and p.get('packages', True) %}

# xccdf_org.ssgproject.content_rule_package_aide_installed
# Install AIDE  [severity: medium]
# PCI-DSS: Req-11.5, 11.5.2
pkg_present_aide:
  pkg.installed:
    - name: aide

# xccdf_org.ssgproject.content_rule_package_audit-audispd-plugins_installed
# Ensure the default plugins for the audit dispatcher are Installed  [severity: medium]
# PCI-DSS: Req-10.5.3, 10.3.3, 10.3
pkg_present_audit-audispd-plugins:
  pkg.installed:
    - name: audit-audispd-plugins

# xccdf_org.ssgproject.content_rule_package_audit_installed
# Ensure the audit Subsystem is Installed  [severity: medium]
# PCI-DSS: Req-10.1, 10.2.1, 10.2
pkg_present_audit:
  pkg.installed:
    - name: audit

# xccdf_org.ssgproject.content_rule_package_chrony_installed
# The Chrony package is installed  [severity: medium]
# PCI-DSS: Req-10.4, 10.6.1, 10.6
pkg_present_chrony:
  pkg.installed:
    - name: chrony

# xccdf_org.ssgproject.content_rule_package_cron_installed
# Install the cron service  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
pkg_present_cron:
  pkg.installed:
    - name: cronie

# xccdf_org.ssgproject.content_rule_package_dhcp_removed
# Uninstall DHCP Server Package  [severity: medium]
# PCI-DSS: 2.2.4, 2.2
pkg_absent_dhcp:
  pkg.removed:
    - name: dhcp-server

# xccdf_org.ssgproject.content_rule_package_firewalld_installed
# Install firewalld Package  [severity: medium]
# PCI-DSS: 1.2.1, 1.2
pkg_present_firewalld:
  pkg.installed:
    - name: firewalld

# xccdf_org.ssgproject.content_rule_package_logrotate_installed
# Ensure logrotate is Installed  [severity: medium]
# PCI-DSS: Req-10.7, 10.5.1, 10.5
pkg_present_logrotate:
  pkg.installed:
    - name: logrotate

# xccdf_org.ssgproject.content_rule_package_net-snmp_removed
# Uninstall net-snmp Package  [severity: unknown]
# PCI-DSS: 2.2.4, 2.2
pkg_absent_net-snmp:
  pkg.removed:
    - name: net-snmp

# xccdf_org.ssgproject.content_rule_package_nftables_installed
# Install nftables Package  [severity: medium]
# PCI-DSS: 1.2.1, 1.2
pkg_present_nftables:
  pkg.installed:
    - name: nftables

# xccdf_org.ssgproject.content_rule_package_rsh-server_removed
# Uninstall rsh-server Package  [severity: high]
# PCI-DSS: 2.2.4, 2.2
pkg_absent_rsh-server:
  pkg.removed:
    - name: rsh-server

# xccdf_org.ssgproject.content_rule_package_rsh_removed
# Uninstall rsh Package  [severity: unknown]
# PCI-DSS: 2.2.4, 2.2
pkg_absent_rsh:
  pkg.removed:
    - name: rsh

# xccdf_org.ssgproject.content_rule_package_sudo_installed
# Install sudo Package  [severity: medium]
# PCI-DSS: 2.2.6, 2.2
pkg_present_sudo:
  pkg.installed:
    - name: sudo

# xccdf_org.ssgproject.content_rule_package_talk-server_removed
# Uninstall talk-server Package  [severity: medium]
# PCI-DSS: 2.2.4, 2.2
pkg_absent_talk-server:
  pkg.removed:
    - name: talk-server

# xccdf_org.ssgproject.content_rule_package_talk_removed
# Uninstall talk Package  [severity: medium]
# PCI-DSS: 2.2.4, 2.2
pkg_absent_talk:
  pkg.removed:
    - name: talk

# xccdf_org.ssgproject.content_rule_package_telnet-server_removed
# Uninstall telnet-server Package  [severity: high]
# PCI-DSS: Req-2.2.2, 2.2.4, 2.2
pkg_absent_telnet-server:
  pkg.removed:
    - name: telnet-server

# xccdf_org.ssgproject.content_rule_package_telnet_removed
# Remove telnet Clients  [severity: low]
# PCI-DSS: 2.2.4, 2.2
pkg_absent_telnet:
  pkg.removed:
    - name: telnet

# xccdf_org.ssgproject.content_rule_package_tftp-server_removed
# Uninstall tftp Package  [severity: high]
# PCI-DSS: 2.2.4, 2.2
pkg_absent_tftp-server:
  pkg.removed:
    - name: tftp

# xccdf_org.ssgproject.content_rule_package_tftp_removed
# Remove tftp Daemon  [severity: low]
# PCI-DSS: 2.2.4, 2.2
pkg_absent_tftp:
  pkg.removed:
    - name: tftp

# xccdf_org.ssgproject.content_rule_package_xinetd_removed
# Uninstall xinetd package if not used by network services  [severity: low]
# PCI-DSS: 2.2.4, 2.2
pkg_absent_xinetd:
  pkg.removed:
    - name: xinetd

# xccdf_org.ssgproject.content_rule_package_ypbind_removed
# Remove NIS Client  [severity: unknown]
# PCI-DSS: 2.2.4, 2.2
pkg_absent_ypbind:
  pkg.removed:
    - name: ypbind

# xccdf_org.ssgproject.content_rule_package_ypserv_removed
# Uninstall ypserv Package  [severity: high]
# PCI-DSS: Req-2.2.2, 2.2.4, 2.2
pkg_absent_ypserv:
  pkg.removed:
    - name: ypserv

{%- endif %}
