# Generated by scap2salt — DO NOT EDIT BY HAND.
# Source: ssg-sle15-ds.xml
# Profile: xccdf_org.ssgproject.content_profile_pci-dss-4
# Generated: 2026-06-06T17:30:52+00:00

# 6 rule(s) in category 'pam'.

{%- set p = salt['pillar.get']('pci_dss_sle15', {}) %}
{%- if p.get('enabled', True) and p.get('pam', True) %}

# xccdf_org.ssgproject.content_rule_cracklib_accounts_password_pam_dcredit
# Set Password Strength Minimum Digit Characters  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: Req-8.2.3, 8.3.6, 8.3
pam_cracklib_cracklib_accounts_password_pam_dcredit:
  cmd.run:
    - name: "f=/etc/pam.d/common-password; grep -qE \"^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so\" \"$f\" || echo \"password requisite pam_cracklib.so\" >> \"$f\"; if grep -qE \"^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so.*\\bdcredit=\" \"$f\"; then sed -ri \"s|(^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so.*\\bdcredit=)[^[:space:]]*|\\1-1|\" \"$f\"; else sed -ri \"s|(^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so\\S*)|\\1 dcredit=-1|\" \"$f\"; fi"
    - unless: "f=/etc/pam.d/common-password; grep -qE \"^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so.*\\bdcredit=-1\\b\" \"$f\""

# xccdf_org.ssgproject.content_rule_cracklib_accounts_password_pam_lcredit
# Set Password Strength Minimum Lowercase Characters  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: Req-8.2.3, 8.3.6, 8.3
pam_cracklib_cracklib_accounts_password_pam_lcredit:
  cmd.run:
    - name: "f=/etc/pam.d/common-password; grep -qE \"^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so\" \"$f\" || echo \"password requisite pam_cracklib.so\" >> \"$f\"; if grep -qE \"^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so.*\\blcredit=\" \"$f\"; then sed -ri \"s|(^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so.*\\blcredit=)[^[:space:]]*|\\1-1|\" \"$f\"; else sed -ri \"s|(^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so\\S*)|\\1 lcredit=-1|\" \"$f\"; fi"
    - unless: "f=/etc/pam.d/common-password; grep -qE \"^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so.*\\blcredit=-1\\b\" \"$f\""

# xccdf_org.ssgproject.content_rule_cracklib_accounts_password_pam_minlen
# Set Password Minimum Length  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: Req-8.2.3, 8.3.6, 8.3
pam_cracklib_cracklib_accounts_password_pam_minlen:
  cmd.run:
    - name: "f=/etc/pam.d/common-password; grep -qE \"^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so\" \"$f\" || echo \"password requisite pam_cracklib.so\" >> \"$f\"; if grep -qE \"^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so.*\\bminlen=\" \"$f\"; then sed -ri \"s|(^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so.*\\bminlen=)[^[:space:]]*|\\112|\" \"$f\"; else sed -ri \"s|(^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so\\S*)|\\1 minlen=12|\" \"$f\"; fi"
    - unless: "f=/etc/pam.d/common-password; grep -qE \"^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so.*\\bminlen=12\\b\" \"$f\""

# xccdf_org.ssgproject.content_rule_cracklib_accounts_password_pam_retry
# Set Password Retry Limit  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: Req-8.1.6, Req-8.1.7, 8.3.4, 8.3
pam_cracklib_cracklib_accounts_password_pam_retry:
  cmd.run:
    - name: "f=/etc/pam.d/common-password; grep -qE \"^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so\" \"$f\" || echo \"password requisite pam_cracklib.so\" >> \"$f\"; if grep -qE \"^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so.*\\bretry=\" \"$f\"; then sed -ri \"s|(^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so.*\\bretry=)[^[:space:]]*|\\13|\" \"$f\"; else sed -ri \"s|(^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so\\S*)|\\1 retry=3|\" \"$f\"; fi"
    - unless: "f=/etc/pam.d/common-password; grep -qE \"^[[:space:]]*password[[:space:]]+requisite[[:space:]]+pam_cracklib\\.so.*\\bretry=3\\b\" \"$f\""

# xccdf_org.ssgproject.content_rule_set_password_hashing_algorithm_commonauth
# Set PAM's Common Authentication Hashing Algorithm  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: Req-8.2.1, 8.3.2, 8.3
pam_unix_set_password_hashing_algorithm_commonauth:
  cmd.run:
    - name: "f=/etc/pam.d/common-auth; grep -qE \"^[[:space:]]*auth[[:space:]]+sufficient[[:space:]]+pam_unix\\.so\" \"$f\" || echo \"auth sufficient pam_unix.so\" >> \"$f\"; grep -qE \"^[[:space:]]*auth[[:space:]]+sufficient[[:space:]]+pam_unix\\.so.*\\bsha512\\b\" \"$f\" || sed -ri \"s|(^[[:space:]]*auth[[:space:]]+sufficient[[:space:]]+pam_unix\\.so\\S*)|\\1 sha512|\" \"$f\""
    - unless: "f=/etc/pam.d/common-auth; grep -qE \"^[[:space:]]*auth[[:space:]]+sufficient[[:space:]]+pam_unix\\.so.*\\bsha512\\b\" \"$f\""

# xccdf_org.ssgproject.content_rule_use_pam_wheel_group_for_su
# Enforce Usage of pam_wheel with Group Parameter for su Authentication  [severity: medium]
# (guarded operational state: imperative remediation, kept idempotent via creates/onlyif/unless)
# PCI-DSS: 2.2.6, 2.2
pam_wheel_use_pam_wheel_group_for_su:
  cmd.run:
    - name: "f=/etc/pam.d/su; grep -qE \"^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so\" \"$f\" || echo \"auth required pam_wheel.so\" >> \"$f\"; if grep -qE \"^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so.*\\bgroup=\" \"$f\"; then sed -ri \"s|(^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so.*\\bgroup=)[^[:space:]]*|\\1sugroup|\" \"$f\"; else sed -ri \"s|(^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so\\S*)|\\1 group=sugroup|\" \"$f\"; fi; grep -qE \"^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so.*\\buse_uid\\b\" \"$f\" || sed -ri \"s|(^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so\\S*)|\\1 use_uid|\" \"$f\""
    - unless: "f=/etc/pam.d/su; grep -qE \"^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so.*\\bgroup=sugroup\\b\" \"$f\" && grep -qE \"^[[:space:]]*auth[[:space:]]+required[[:space:]]+pam_wheel\\.so.*\\buse_uid\\b\" \"$f\""

{%- endif %}
